version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '3306:3306' # ホストからゲストへポートフォワード
    environment:
      MYSQL_DATABASE: habiter_development
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:    #追加
      RAILS_ENV: development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
     # pry-byebugを使えるようにする
    tty: true 
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/habiter # ソースコード変更したらDocker側も即反映されるように